### ISSUE TITLE
Search field for Wiki

### ISSUE THREAD

**Issue by rasatpc** [fvwmorg/fvwmorg.github.io#31]
Is it possible to add search functionality to Jekyll website? The wiki is well organized finding major topics. But to help the users find the right specific information as effectively as possible becomes important. Find particular words without understanding or exploring the entire website.

I have no experience creating a search code, but this link looks quite interesting.
https://abhigupta.io/2022/04/02/add-search-jekyll-blog.html

**Comment by somiaj** [comment]
I really don't want to add a lot of javascript and other framework dependencies to the site. I do see what that link is doing, but since we don't use collections, it would take a bit more work. Also what would we want people to search one. We would probably have to first better tag things.

I tried to make the website tree fairly self explanatory, though maybe better explaining the structure could help. But The main wiki root page, fvwm.org/Wiki, contains all the main categories, Config, Decor, CookBook, Tips, Panels, and Modules, and each of those categories lists all the pages they have as children, which to me is a list of all the pages.

**Comment by somiaj** [comment]
Thinking about this a bit more, I guess we could search on the page descriptions in the wiki which does give text we can search on. I just don't see a javascript search being that good compared to a real search engines. In the end there is really no reason we need to build our own search engine when there are other ones out there (in fact lost of sites these days just use google to search their sites).

For instance people can already use `site:fvwm.org` with google and only search fvwm, so us building a not as good search engine seems like time that would be better spent first filling up some of the missing/blank places in the wiki, updating the outdated information, and so on.

**Comment by rasatpc** [comment]
> sites these days just use google

As an example, searching for a specific word like Ivar's forum comment about "ItemFormat" ........ "there is a new manual page on Fvwm Web site". After a while, Google will include it. But it would be nice to stay there finding other related words without Google. The Manual Page is a huge source of information.

I will check around.

**Comment by somiaj** [comment]
There is no reason to build and maintain search functionality on this site. This is not something that will be accepted.
